/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageRole = IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null });
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'contactInfo' : IDL.Text,
  'totalAmount' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'product' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : IDL.Int,
});
export const BotStep = IDL.Variant({
  'askProduct' : IDL.Null,
  'confirmOrder' : IDL.Null,
  'greeting' : IDL.Null,
  'askContact' : IDL.Null,
  'complete' : IDL.Null,
  'askQuantity' : IDL.Null,
  'askAddress' : IDL.Null,
});
export const ChatSession = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Opt(IDL.Text),
  'contactInfo' : IDL.Opt(IDL.Text),
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
  'currentStep' : BotStep,
  'address' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Opt(IDL.Nat),
  'product' : IDL.Opt(IDL.Text),
  'linkedOrderId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Nat, MessageRole, IDL.Text], [], []),
  'createChatSession' : IDL.Func([], [IDL.Nat], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBotResponse' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'getChatSession' : IDL.Func([IDL.Nat], [ChatSession], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'updateChatSessionStep' : IDL.Func([IDL.Nat, BotStep], [], []),
  'updateCustomerName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageRole = IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'contactInfo' : IDL.Text,
    'totalAmount' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'product' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : IDL.Int,
  });
  const BotStep = IDL.Variant({
    'askProduct' : IDL.Null,
    'confirmOrder' : IDL.Null,
    'greeting' : IDL.Null,
    'askContact' : IDL.Null,
    'complete' : IDL.Null,
    'askQuantity' : IDL.Null,
    'askAddress' : IDL.Null,
  });
  const ChatSession = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Opt(IDL.Text),
    'contactInfo' : IDL.Opt(IDL.Text),
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
    'currentStep' : BotStep,
    'address' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Opt(IDL.Nat),
    'product' : IDL.Opt(IDL.Text),
    'linkedOrderId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Nat, MessageRole, IDL.Text], [], []),
    'createChatSession' : IDL.Func([], [IDL.Nat], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBotResponse' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'getChatSession' : IDL.Func([IDL.Nat], [ChatSession], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'updateChatSessionStep' : IDL.Func([IDL.Nat, BotStep], [], []),
    'updateCustomerName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };