/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BotStep = { 'askProduct' : null } |
  { 'confirmOrder' : null } |
  { 'greeting' : null } |
  { 'askContact' : null } |
  { 'complete' : null } |
  { 'askQuantity' : null } |
  { 'askAddress' : null };
export interface ChatSession {
  'id' : bigint,
  'customerName' : [] | [string],
  'contactInfo' : [] | [string],
  'messages' : Array<Message>,
  'createdAt' : bigint,
  'currentStep' : BotStep,
  'address' : [] | [string],
  'quantity' : [] | [bigint],
  'product' : [] | [string],
  'linkedOrderId' : [] | [bigint],
}
export interface Message {
  'content' : string,
  'role' : MessageRole,
  'timestamp' : bigint,
}
export type MessageRole = { 'bot' : null } |
  { 'user' : null };
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'contactInfo' : string,
  'totalAmount' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
  'shippingAddress' : string,
  'product' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface _SERVICE {
  'addMessage' : ActorMethod<[bigint, MessageRole, string], undefined>,
  'createChatSession' : ActorMethod<[], bigint>,
  'createOrder' : ActorMethod<
    [string, string, bigint, string, string, string],
    bigint
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBotResponse' : ActorMethod<[bigint, string], string>,
  'getChatSession' : ActorMethod<[bigint], ChatSession>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'updateChatSessionStep' : ActorMethod<[bigint, BotStep], undefined>,
  'updateCustomerName' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];